export const reservations = [
  {
    id: 'HD-2024',
    guest: 'Santiago Reyes',
    email: 'santiago.reyes@email.com',
    avatar: 'https://i.pravatar.cc/64?img=12',
    room: '401',
    roomType: 'Suite',
    checkIn: '2024-07-31',
    checkOut: '2024-08-04',
    nights: 4,
    status: 'Checked-in',
    payment: 'Paid',
    source: 'Direct',
    amount: 60000,
  },
  {
    id: 'HD-2025',
    guest: 'Maria Santos',
    email: 'maria.santos@email.com',
    avatar: 'https://i.pravatar.cc/64?img=5',
    room: '201',
    roomType: 'Deluxe',
    checkIn: '2024-07-31',
    checkOut: '2024-08-02',
    nights: 2,
    status: 'Confirmed',
    payment: 'Paid',
    source: 'Booking.com',
    amount: 13000,
  },
  {
    id: 'HD-2026',
    guest: 'James Lim',
    email: 'james.lim@email.com',
    avatar: 'https://i.pravatar.cc/64?img=15',
    room: '203',
    roomType: 'Deluxe',
    checkIn: '2024-08-01',
    checkOut: '2024-08-03',
    nights: 2,
    status: 'Pending',
    payment: 'Partial',
    source: 'Agoda',
    amount: 12000,
  },
  {
    id: 'HD-2027',
    guest: 'Ana Villanueva',
    email: 'ana.v@email.com',
    avatar: 'https://i.pravatar.cc/64?img=9',
    room: '501',
    roomType: 'Presidential Suite',
    checkIn: '2024-08-01',
    checkOut: '2024-08-07',
    nights: 6,
    status: 'Confirmed',
    payment: 'Paid',
    source: 'Direct',
    amount: 270000,
  },
  {
    id: 'HD-2028',
    guest: 'Carlos Mendoza',
    email: 'carlos.mendoza@email.com',
    avatar: 'https://i.pravatar.cc/64?img=33',
    room: '305',
    roomType: 'Deluxe',
    checkIn: '2024-08-02',
    checkOut: '2024-08-04',
    nights: 2,
    status: 'Confirmed',
    payment: 'Paid',
    source: 'Expedia',
    amount: 13000,
  },
  {
    id: 'HD-2029',
    guest: 'Grace Tan',
    email: 'grace.tan@email.com',
    avatar: 'https://i.pravatar.cc/64?img=25',
    room: '102',
    roomType: 'Standard',
    checkIn: '2024-08-03',
    checkOut: '2024-08-05',
    nights: 2,
    status: 'Confirmed',
    payment: 'Partial',
    source: 'Direct',
    amount: 8000,
  },
  {
    id: 'HD-2030',
    guest: 'Michael Cruz',
    email: 'michael.cruz@email.com',
    avatar: 'https://i.pravatar.cc/64?img=51',
    room: '404',
    roomType: 'Suite',
    checkIn: '2024-08-05',
    checkOut: '2024-08-06',
    nights: 1,
    status: 'Pending',
    payment: 'Unpaid',
    source: 'Agoda',
    amount: 15000,
  },
  {
    id: 'HD-2031',
    guest: 'Isabel Ramos',
    email: 'isabel.ramos@email.com',
    avatar: 'https://i.pravatar.cc/64?img=47',
    room: '202',
    roomType: 'Deluxe',
    checkIn: '2024-07-28',
    checkOut: '2024-07-31',
    nights: 3,
    status: 'Checked-out',
    payment: 'Paid',
    source: 'Booking.com',
    amount: 19500,
  },
]
